### ISSUE TITLE
WAAPI instead of CSS

### ISSUE THREAD

**Issue by jdnichollsc** [natemoo-re/animate-presence#2]
What do you think if you use WAAPI instead of CSS? Check https://github.com/proyecto26/animatable-component

Let me know

**Comment by natemoo-re** [comment]
Nice, I was wondering if something like that existed! I'd definitely like to add support for WAAPI somehow, but I'm not sure what that would look like yet.

**Comment by jdnichollsc** [comment]
Try and let me know! 👯‍♂

**Comment by natemoo-re** [comment]
I opened a PR (#3) for this! 

It was pretty minor to enable, and actually simplified the logic I was using to detect animations previously. 😄

This approach feels nice and generic, but it's obviously imperative. A declarative option would be nice, but I don't think I want to add that just yet. If you have any thoughts, I'd love to hear them!

**Comment by jdnichollsc** [comment]
I'm creating some examples using Animatable => https://codepen.io/jdnichollsc/pen/OJVWyQm?editors=1010
